### ISSUE TITLE
Consider adding CompatHelper

### ISSUE THREAD

**Issue by SebastianM-C** [JuliaAstro/LombScargle.jl#13]
I think that this repo may benefit from adding CompatHelper. For example `SpecialFunctions` is now at  [v.0.10.0](https://github.com/JuliaMath/SpecialFunctions.jl/releases/tag/v0.10.0) and the compat bounds must be updated.

I can make a PR if you want.

**Comment by giordano** [comment]
> I can make a PR if you want.

Yes please

**Comment by SebastianM-C** [comment]
See #14

**Comment by SebastianM-C** [comment]
Fixed by #14
