### ISSUE TITLE
The generalised Lomb-Scargle periodogram

### ISSUE THREAD

**Issue by citron** [JuliaAstro/LombScargle.jl#27]
Hello
Does this algorithm implement the generalised Lomb-Scargle periodogram as described in [The generalised Lomb-Scargle periodogram - A new formalism for the floating-mean and Keplerian periodograms, 
M. Zechmeister and M. Kürster](https://doi.org/10.1051/0004-6361:200811296) ? ( [pdf here](https://www.aanda.org/articles/aa/pdf/2009/11/aa11296-08.pdf)  ) 
If not, do you please have any plan to integrate it ?
Thanks

**Comment by giordano** [comment]
Did you try to search for "generalised" in the [documentation](https://juliaastro.github.io/LombScargle.jl/stable/)? 🙂

**Comment by citron** [comment]
> Did you try to search for "generalised" in the [documentation](https://juliaastro.github.io/LombScargle.jl/stable/)? 🙂

I am so dumb ! I did, but with the american-english spelling... generaliZed.
Thanks and sorry for the disturbance
