### ISSUE TITLE
Docs Error for PSD normalization?

### ISSUE THREAD

**Issue by JacobLuhn** [JuliaAstro/LombScargle.jl#28]
After comparing with [ZK09] and the Astropy documentation, I believe the normalization between PSD and standard has a typo in the [documentation](https://juliaastro.github.io/LombScargle.jl/stable/#Normalization) and should be:

       P(f) = p(f) * W * YY / 2

(i.e., there is currently a W missing). [Astropy documentation lists the unnormalized psd to be ](https://docs.astropy.org/en/stable/timeseries/lombscargle.html#periodogram-normalizations)

       P_psd(f) = 0.5* (Chi^2_ref - Chi^2(f)

whereas [ZK09] writes

       P_standard(f) = (Chi^2_ref - Chi^2(f)) / (Chi^2_ref)

So to transform between the two, you must multiply by Chi^2_ref/2, and [ZK09] gives Chi^2_ref as W * YY

After testing a few datasets, including a W term does indeed produce identical periodograms.

**Comment by giordano** [comment]
`W` is the sum of the inverse of the chis squared, right?  PSD normalisation is indeed
https://github.com/JuliaAstro/LombScargle.jl/blob/cb584adf8c2920c4499ffbac47edd8c46c882647/src/LombScargle.jl#L59
where `psdfactor` is `YY * sumw`
https://github.com/JuliaAstro/LombScargle.jl/blob/454e08d9e52dcf59f6a3d3df0d025cdf32fea40e/src/LombScargle.jl#L73
and this `sumw` is indeed the `W` above:
https://github.com/JuliaAstro/LombScargle.jl/blob/454e08d9e52dcf59f6a3d3df0d025cdf32fea40e/src/planning.jl#L137-L138
So it does look like there is an error in the documentation but the code is good.

Would you mind opening a pull request fixing the error?  :slightly_smiling_face:   Please remember to define `W`

**Comment by JacobLuhn** [comment]
Ok, I think the pull request should fix it. I'm still new to Git so let me know if there's anything else I need to do/change for the pull request.
