### ISSUE TITLE
`latest` docs on RTD show only default index page

### ISSUE THREAD

**Issue by dnadlinger** [JuliaAstro/LombScargle.jl#9]
The README contains a link to https://lombscarglejl.readthedocs.io/en/latest/#planning-the-periodogram, but that shows the RTD default index rather than the root manual page. https://lombscarglejl.readthedocs.io/en/v0.0.2/ is fine.

**Comment by giordano** [comment]
Thanks for spotting this!  Documentation actually moved to https://juliaastro.github.io/LombScargle.jl/stable/.  Will be fixed by #10

**Comment by dnadlinger** [comment]
Ah, makes sense – thanks for the quick response!
